---
title: "Methamphetmine Use and Driving Behaviour"
subtitle: "Predictors of dangerous driving behaviour in Methamphetamine users (a quick look at our sample)"
author: "Aaron Mackay"
institute: "Swinburne University Centre for Human Psychopharmacology"
date: "Updated: `r Sys.Date()`"
output: xaringan::moon_reader
  
  
---

```{css, echo = FALSE}
tableContainer{
  height: 300px;
  overflow: hidden;
}

table{
  font-size: 10px;
  position: sticky;
  top: 0;
  width: 100%;
}

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
load("objects/all-objects.RData")

packages <- c("tidyverse", "janitor", "table1", "gt", "naniar", "kableExtra", "DT", "plotly")
librarian::shelf(packages)

theme_set(theme_light())
```

# Demographics
```{r}
dems.tbl %>% t1kable(format = "html") %>% scroll_box(height = "500px")
```

---
# Assessments
```{r}
ass.tbl %>% t1kable(format = "html") %>% scroll_box(height = "500px")
```

---
# Assessments (cont.)
```{r}
suppressWarnings(
ggplotly(ass.plot, width = 800, height = 500)
)
```

# Next Steps


## Shit
This is text

``` r
code <- "test"
```
This is __bold.__

This is _italics_


```{r cars, echo = TRUE}
summary(cars)
```

## Slide with Plot

```{r pressure}
plot(pressure)
```
